---
- name: "Add VLAN Bridge/Interface"
  hosts: MikrotikKNOT
  vars:
  - ansible_connection: ansible.netcommon.network_cli
  - ansible_network_os: community.network.routeros
  - ANSIBLE_REMOTE_TMP: /tmp
  gather_facts: false
  environment:
    remote_tmp:  /tmp/.ansible/tmp

  tasks:

    - name: Check version
      raw: /system package update check-for-updates

    - name: Check if an update is needed
      routeros_command:
        commands:
          - "[:put ([/system package update check-for-updates])]"
      register: output
    - name: print variable
      debug:
        msg: "{{ output }}"
    - name: Run upgrade if new version is available
      routeros_command:
        commands:
           - /system package update install
      when: output.stdout is search('available')


   - name: Performing backup of Mikrotik to local storage
     raw: /system backup save name {{inventory_hostname}}
...
