---
  #VLAN für Bridge/Interface anlegen und interfaces "tagged"/"untagged" hinzufügen.
  #Zusätzlich Kommentare möglich

- name: "Add VLAN Bridge/Interface"
  hosts: SwitcheCore:SwitcheIDF
  vars:
  - ansible_connection: ansible.netcommon.network_cli
  - ansible_network_os: community.network.routeros
  - ANSIBLE_REMOTE_TMP: /tmp

#Variablen für die VLANs
    vlanid: 2030
    vlanname: testvlan30
    bridgeid: bridge
    untaggedinterfacetrunk: ""
    taggedinterfacecoretrunk: bridge,sfp-sfpplus1,sfp-sfpplus2,sfp-sfpplus3,sfp-sfpplus4,sfp-sfpplus5,sfp-sfpplus6,sfp-sfpplus7,sfp-sfpplus8,sfp-sfpplus9,sfp-sfpplus10,sfp-sfpplus11,sfp-sfpplus12,sfp-sfpplus13,sfp-sfpplus14,sfp-sfpplus15,sfp-sfpplus16,sfp-sfpplus17,sfp-sfpplus18,sfp-sfpplus19,sfp-sfpplus20,sfp-sfpplus21,sfp-sfpplus22,sfp-sfpplus23,sfp-sfpplus24,qsfpplus1-1,qsfpplus1-2,qsfpplus1-3,qsfpplus1-4,qsfpplus2-1,qsfpplus2-2,qsfpplus2-3,qsfpplus2-4
    taggedinterfaceidftrunk: bridge,sfp-sfpplus1,sfp-sfpplus2,sfp-sfpplus3,sfp-sfpplus4
    taggedinterfaceidfaccess: bridge1,sfp-sfpplus1,sfp-sfpplus2,sfp-sfpplus3,sfp-sfpplus4,ether1
    commentvar: VLAN {{ vlanid }}: Nutzung für


  gather_facts: false
  environment:
    remote_tmp:  /tmp/.ansible/tmp

  tasks:
    - debug:
        msg: Add VLAN

- name: Add VLAN SwitcheCore(Trunk)
  import_playbook: pb_mk_vlan-add-SwitcheCore.yml

- name: Add VLAN SwitcheIDF (Trunk)
  import_playbook: pb_mk_vlan-add-SwitcheIDF-Trunk.yml

- name: Add VLAN SwitcheIDF (Access)
  import_playbook: pb_mk_vlan-add-SwitcheCore-Access.yml
