---
- name: "Upgrade"
  hosts: all
  vars:
  - ansible_connection: ansible.netcommon.network_cli
  - ansible_network_os: community.network.routeros
  - ANSIBLE_REMOTE_TMP: /tmp
  gather_facts: false
  environment:
    remote_tmp:  /tmp/.ansible/tmp

  tasks:

#  - name: Upgade to latest stable
#    community.routeros.command:
#      commands: /system package update install

    - name: aktuelle Version
      community.routeros.command:
        commands:
          - /system package print
          register: version-output

    - name: print variable
      debug:
        msg: "{{ version-output }}"

    - name: update-check Version
      community.routeros.command:
        commands:
          - /system package update update-check
        register: version-new-output

      - name: print variable2
        debug:
          msg: "{{ version-new-output }}"

  #- name: Check if an update is needed
  #  community.routeros.command:
  #    commands:
  #      - "[:put ([/system package update check-for-updates])]"
  #  register: output

  #  - name: print variable
  #    debug:
  #      msg: "{{ output }}"

      - name: Run upgrade if new version is available
        community.routeros.command:
          commands:
            - /system package update install
            when: version-new-output is search('available')


#   - name: Performing backup of Mikrotik to local storage
#     raw: /system backup save name {{inventory_hostname}}
...
