---
- name: "Add VLAN Bridge/Interface"
  hosts: all
  vars:
  - ansible_connection: ansible.netcommon.network_cli
  - ansible_network_os: community.network.routeros
  - ANSIBLE_REMOTE_TMP: /tmp
    vlanid: 2009
    vlanname: testvlan
    bridgeid: bridge1
    taggedinterface: ether1
    untaggedinterface: ether2,bridge1
  gather_facts: false
  environment:
    remote_tmp:  /tmp/.ansible/tmp

  tasks:

  - name: VLAN Add Interface
    community.routeros.command:
      commands: /interface/vlan/add vlan-id=[vlanid] interface=[bridgeid] name=[vlanname]

  - name: VLAN Add Interface 2009
    community.routeros.command:
      commands: /interface/vlan/add vlan-id=2009 interface=bridge1 name=testvlan

  - name: VLAN Add Bridge
    community.routeros.command:
      commands: /interface/bridge/vlan/add vlan-id=[vlanid] bridge=[bridgeid] untagged=[untaggedinterface] tagged=[taggedinterface]


...
