---
- name: "RoMon"
  hosts: all
  vars:
  - ansible_connection: ansible.netcommon.network_cli
  - ansible_network_os: community.network.routeros
  - ANSIBLE_REMOTE_TMP: /tmp

  gather_facts: false
  environment:
    remote_tmp:  /tmp/.ansible/tmp



  tasks:


  - name: "disable sensitive service"
    community.routeros_command:
      commands: /ip service disable {{ item }}
    with_items:
    - telnet
    - ftp
    - www
    - api
    - api-ssl
