---
  #VLAN für Bridge/Interface anlegen und interfaces "tagged"/"untagged" hinzufügen.
  #Zusätzlich Kommentare möglich

- name: "Add VLAN Bridge/Interface"
  hosts: SwitcheIDF
  vars:
  - ansible_connection: ansible.netcommon.network_cli
  - ansible_network_os: community.network.routeros
  - ANSIBLE_REMOTE_TMP: /tmp

#Variablen für die VLANs
    vlanid: 4001
    vlanname: USV
    bridgeid: bridge
    untaggedinterface: ""
    taggedinterfaceidftrunk: bridge,sfp-sfpplus1,sfp-sfpplus2,sfp-sfpplus3,sfp-sfpplus4
    commentvar: "VLAN {{ vlanid }}: Nutzung für USV"


  gather_facts: false
  environment:
    remote_tmp:  /tmp/.ansible/tmp

  tasks:

#VLAN entfernen, falls es bereits angelegt wurde, um es entsprechend neu anzulegen
  - name: VLAN entfernen vorm anlegen {{ vlanid }}
    community.routeros.command:
      commands: /interface/bridge/vlan/remove [find vlan-ids={{ vlanid }}]

#VLAN im Bereich Interface anlegen.
  - name: VLAN Add Interface {{ vlanid }}
    community.routeros.command:
      commands: /interface/vlan/add vlan-id={{ vlanid }} interface={{ bridgeid }} name={{ vlanname }}  comment={{commentvar}}

#VLAN Interface einstellungen setzen
  - name: VLAN Set Interface {{ vlanid }}
    community.routeros.command:
      commands: /interface/vlan/set [find vlan-id={{ vlanid }}] interface={{ bridgeid }} name={{ vlanname }}  comment={{commentvar}}

#VLAN im Bereich Bridge entfernen, um es entsprechend neu anzulegen
  - name: VLAN entfernen vorm anlegen {{ vlanid }}
    community.routeros.command:
      commands: /interface/bridge/vlan/remove [find vlan-ids={{ vlanid }}]

#VLAN im Bereich Bridge hinzufügen und Ports tagged/untagged eintragen
  - name: VLAN Add Bridge {{ vlanid }}
    community.routeros.command:
      commands:
        - "/interface/bridge/vlan/add vlan-id={{ vlanid }} bridge={{ bridgeid }} tagged={{ taggedinterfaceidftrunk }} untagged={{ untaggedinterfacetrunk }} comment={{commentvar}}"


...
