---
  #VLAN für Bridge/Interface anlegen und interfaces "tagged"/"untagged" hinzufügen.
  #Zusätzlich Kommentare möglich

- name: "Add VLAN Bridge/Interface"
  hosts: SwitcheCore:SwitcheIDF
  vars:
  - ansible_connection: ansible.netcommon.network_cli
  - ansible_network_os: community.network.routeros
  - ANSIBLE_REMOTE_TMP: /tmp

  gather_facts: false
  environment:
    remote_tmp:  /tmp/.ansible/tmp

  tasks:
    - debug:
        msg: Add VLAN

- name: Add VLAN SwitcheCore(Trunk)
  import_playbook: pb_mk_vlan-add-SwitcheCore.yml

- name: Add VLAN SwitcheIDF (Trunk)
  import_playbook: pb_mk_vlan-add-SwitcheIDF-Trunk.yml

- name: Add VLAN SwitcheIDF (Access)
  import_playbook: pb_mk_vlan-add-SwitcheIDF-Access.yml
