---
- name: "Add VLAN Bridge/Interface"
  hosts: all
  vars:
  - ansible_connection: ansible.netcommon.network_cli
  - ansible_network_os: community.network.routeros
  - ANSIBLE_REMOTE_TMP: /tmp
    vlanid: 2011
    vlanname: testvlan3
    bridgeid: bridge1
    taggedinterface: ether2
    untaggedinterface: ether1, bridge1
    commentvar: Ansible
  gather_facts: false
  environment:
    remote_tmp:  /tmp/.ansible/tmp

  tasks:

  - name: VLAN Add Interface {{ vlanid }}
    community.routeros.command:
      commands: /interface/vlan/add vlan-id={{ vlanid }} interface={{ bridgeid }} name={{ vlanname }}  comment={{commentvar}}

#  - name: VLAN Add Interface 2009
#    community.routeros.command:
#      commands: /interface/vlan/add vlan-id=2009 interface=bridge1 name=testvlan

  - name: VLAN Add Bridge {{ vlanid }}
    community.routeros.command:
      commands: /interface/bridge/vlan/add vlan-id={{ vlanid }} bridge={{ bridgeid }} tagged={{ taggedinterface }} untagged={{ untaggedinterface }} comment={{commentvar}}

#  - name: VLAN Add Bridge 2009
#    community.routeros.command:
#      commands: /interface/bridge/vlan/add vlan-id=2009 bridge=bridge1 untagged=ether1 tagged=ether2

...
