---
- name: "Check OS Version"
  hosts: all
  vars:
  - ansible_connection: ansible.netcommon.network_cli
  - ansible_network_os: community.network.routeros
  - ANSIBLE_REMOTE_TMP: /tmp
  gather_facts: false
  environment:
    remote_tmp:  /tmp/.ansible/tmp

  tasks:
  - name: Check OS Version on Device
    community.routeros.command:
      commands: /system package print
    register: version_output

  - name: Display Facts Variable
    debug:
      var: version_output
...
