---
- name: "RoMon"
  hosts: all
  vars:
  - ansible_connection: ansible.netcommon.network_cli
  - ansible_network_os: community.network.routeros
  - ANSIBLE_REMOTE_TMP: /tmp
    routeros_timezone: "Europe/Berlin"

  gather_facts: false
  environment:
    remote_tmp:  /tmp/.ansible/tmp



  tasks:

  - name: setup timezone
    community.routeros.command:
      commands:
          - "/system clock set time-zone-autodetect=no time-zone-name={{ routeros_timezone }}"
