---
- name: "SNMP"
  hosts: all
  vars:
  - ansible_connection: ansible.netcommon.network_cli
  - ansible_network_os: community.network.routeros
  - ANSIBLE_REMOTE_TMP: /tmp

#Variablen für die SNMP Einstellungen Community/Location
    snmpcommunity: setnetz
    snmplocation: Lager

  gather_facts: false
  environment:
    remote_tmp:  /tmp/.ansible/tmp



  tasks:

  - name: Set community
    community.routeros.command:
      commands: /snmp/community/add name={{snmpcommunity}} read-access=yes write-access=no

  - name: Set Port Description leeren
    community.routeros.command:
      commands: /snmp/set enabled=yes location={{snmplocation}} trap-community={{snmpcommunity}}

...
