---
- name: "Port Description"
  hosts: MikrotikKNOT
  vars:
  - ansible_connection: ansible.netcommon.network_cli
  - ansible_network_os: community.network.routeros
  - ANSIBLE_REMOTE_TMP: /tmp

#Variablen für die VLANs
    vlanid: 2030
    #vlanname wird zur Benennung des Ports/comment definiert
    vlanname: testvlan30
    bridgeid: bridge1
    taggedinterface: ether2
    untaggedinterface: ether1,bridge1
    commentvar: VLAN 2030: Nutzung für
    #Ethernet/SFP-Port (Hardware)
    portid: ether1

  gather_facts: false
  environment:
    remote_tmp:  /tmp/.ansible/tmp



  tasks:

  - name: Set Port Description leeren
    community.routeros.command:
      commands: /interface/set [find name={{ portid }}] comment=""

  - name: Set Port Description leeren
    community.routeros.command:
      commands: /interface/set [find name={{ portid }}] comment="{{ vlanname }}"

  #- name: Check if an update is needed
  #  community.routeros.command:
  #    commands:
  #      - "[:put ([/system package update check-for-updates])]"
  #  register: output
#
#    - name: print variable
#      debug:
#        msg: "{{ output }}"
#
#    - name: Run upgrade if new version is available
#      community.routeros.command:
#        commands:
#           - /system package update install
#      when: output.stdout is search('available')


#   - name: Performing backup of Mikrotik to local storage
#     raw: /system backup save name {{inventory_hostname}}
...
