---
  #VLAN für Bridge/Interface einstellen und interfaces "tagged"/"untagged" hinzufügen.
  #Zusätzlich Kommentare möglich

- name: "Set VLAN Bridge/Interface"
  hosts: MikrotikKNOT
  vars:
  - ansible_connection: ansible.netcommon.network_cli
  - ansible_network_os: community.network.routeros
  - ANSIBLE_REMOTE_TMP: /tmp

#Variablen für die VLANs
    vlanid: 2030
    vlanname: testvlan30
    bridgeid: bridge1
    taggedinterface: ether2
    untaggedinterface: ether1,bridge1
    commentvar: Ansible30


  gather_facts: false
  environment:
    remote_tmp:  /tmp/.ansible/tmp

  tasks:


#VLAN Interface einstellungen setzen
  - name: VLAN Set Interface {{ vlanid }}
    community.routeros.command:
      commands: /interface/vlan/set [find vlan-id={{ vlanid }}] interface={{ bridgeid }} name={{ vlanname }}  comment={{commentvar}}


#VLAN im Bereich Bridge hinzufügen und Ports tagged/untagged eintragen
  - name: VLAN Add Bridge {{ vlanid }}
    community.routeros.command:
      commands:
        - "/interface/bridge/vlan/set [find vlan-id={{ vlanid }}] bridge={{ bridgeid }} tagged={{ taggedinterface }} untagged={{ untaggedinterface }} comment={{commentvar}}"



...
