#################################################################
#das Upgrade funktioniert nicht ohne manuelle Bestätigungg      #
#Damit Upgrade nur als "Autoupgrade" bei nächstem Restart       #
#Freigabe zur Verwendung                                        #
#################################################################

---
- name: "Upgrade"
  hosts: all
  vars:
  - ansible_connection: ansible.netcommon.network_cli
  - ansible_network_os: community.network.routeros
  - ANSIBLE_REMOTE_TMP: /tmp
  gather_facts: false
  environment:
    remote_tmp:  /tmp/.ansible/tmp

    tasks:

    - name: Set Autoupgrade auf yes, Firmwareupgrade bei nächstem Restart
      community.routeros.command:
        commands:
          -  /system routerboard settings set auto-upgrade=yes


  #- name: Check if an update is needed
  #  community.routeros.command:
  #    commands:
  #      - "[:put ([/system package update check-for-updates])]"
  #  register: output
#
#    - name: print variable
#      debug:
#        msg: "{{ output }}"
#
#    - name: Run upgrade if new version is available
#      community.routeros.command:
#        commands:
#           - /system package update install
#      when: output.stdout is search('available')


#   - name: Performing backup of Mikrotik to local storage
#     raw: /system backup save name {{inventory_hostname}}
...
