---
- name: "Wlan entfernen"
  hosts: hAPAX3
  vars:
  - ansible_connection: ansible.netcommon.network_cli
  - ansible_network_os: community.network.routeros
  - ANSIBLE_REMOTE_TMP: /tmp

#Variablen für die VLANs
  - ssidconfig:
    value1: GBDF-Backstage2023
    value2: GBDF-Checkin
    value3: GBDF-Presse
    value4: GBDF-RedCarpet
    value5: RBF2023Ticketing
    value6: StageTheaterNeueFlora
    value7: "RBF2023 Produktion"
    value8: "RBF2023 Stages"

  gather_facts: false
  environment:
    remote_tmp:  /tmp/.ansible/tmp



  tasks:

  - name: WLAN entfernen
    community.routeros.command:
      commands: /interface/wifi/remove [find configuration={{ ssidconfig }}]
