---
- name: RouterOS test with network_cli connection
  hosts: all
  vars:
  - ansible_connection: ansible.netcommon.network_cli
  - ansible_network_os: community.network.routeros
  - ANSIBLE_REMOTE_TMP: /tmp
  gather_facts: false
  environment:
    remote_tmp:  /tmp/.ansible/tmp

  tasks:

  - name: Gather system resources
    community.routeros.command:
      commands:
        - /system resource print
    register: system_resource_print

  - name: Show system resources
    debug:
      var: system_resource_print.stdout_lines

  - name: Gather facts
    community.routeros.facts:

  - name: Show a fact
    debug:
      msg: "First IP address: {{ ansible_net_all_ipv4_addresses[0] }}"
...
