---
- name: "Check OS Version"
  hosts: all
  gather_facts: no


  tasks:
  - name: Check OS Version on Device
    community.routeros.command:
      commands: /system package print
    register: version_output

  - name: Display Facts Variable
    debug:
      var: version_output
...
