---
  #VLAN für Bridge/Interface entfernen und interfaces "tagged"/"untagged" löschen.
  #Zusätzlich Kommentare möglich

- name: "remove VLAN Bridge/Interface"
  hosts: all
  vars:
  - ansible_connection: ansible.netcommon.network_cli
  - ansible_network_os: community.network.routeros
  - ANSIBLE_REMOTE_TMP: /tmp

#Variablen für die VLANs
    vlanid: 50
    vlanname: testvlan30
    bridgeid: bridge1
    taggedinterface: ether2
    untaggedinterface: ether1,bridge1
    commentvar: Ansible30


  gather_facts: false
  environment:
    remote_tmp:  /tmp/.ansible/tmp

  tasks:

#VLAN entfernen, falls es bereits angelegt wurde, um es entsprechend neu anzulegen
  - name: VLAN entfernen {{ vlanid }}
    community.routeros.command:
      commands: /interface/vlan/remove [find vlan-id={{ vlanid }}]


#VLAN im Bereich Bridge entfernen, um es entsprechend neu anzulegen
  - name: VLAN entfernen {{ vlanid }}
    community.routeros.command:
      commands: /interface/bridge/vlan/remove [find vlan-ids={{ vlanid }}]

...
