---
- name: RouterOS Status
  hosts: all
  vars:
  - ansible_connection: ansible.netcommon.network_cli
  - ansible_network_os: community.network.routeros
  - ANSIBLE_REMOTE_TMP: /tmp
  gather_facts: false
  environment:
    remote_tmp:  /tmp/.ansible/tmp

  tasks:

  - name: Run command on remote devices
    community.routeros.command:
      commands: /system routerboard print

  - name: Run command and check to see if output contains routeros
    community.routeros.command:
      commands: /system resource print
      wait_for: result[0] contains MikroTik

  - name: Run multiple commands on remote nodes
    community.routeros.command:
      commands:
        - /system routerboard print
        - /system identity print

  - name: Run multiple commands and evaluate the output
    community.routeros.command:
      commands:
        - /system routerboard print
        - /interface ethernet print
      wait_for:
        - result[0] contains x86
        - result[1] contains ether1
...
