---
  #VLAN für Bridge/Interface anlegen und interfaces "tagged"/"untagged" hinzufügen.
  #Zusätzlich Kommentare möglich

- name: "Add VLAN Bridge/Interface"
  hosts: all
  vars:
  - ansible_connection: ansible.netcommon.network_cli
  - ansible_network_os: community.network.routeros
  - ANSIBLE_REMOTE_TMP: /tmp

#Variablen für die VLANs
    vlanid: 2014
    vlanname: testvlan20
    bridgeid: bridge1
    taggedinterface: ether2
    untaggedinterface: ether1,bridge1
    commentvar: Ansible21


  gather_facts: false
  environment:
    remote_tmp:  /tmp/.ansible/tmp

  tasks:
  - name: VLAN entfernen vorm anlegen {{ vlanid }}
    community.routeros.command:
      commands: /interface/bridge/vlan/remove [find vlan-ids={{ vlanid }}]


  - name: VLAN Add Interface {{ vlanid }}
    community.routeros.command:
      commands: /interface/vlan/add vlan-id={{ vlanid }} interface={{ bridgeid }} name={{ vlanname }}  comment={{commentvar}}

  - name: VLAN Set Interface {{ vlanid }}
    community.routeros.command:
      commands: /interface/vlan/set [find vlan-ids={{ vlanid }}] interface={{ bridgeid }} name={{ vlanname }}  comment={{commentvar}}


  - name: VLAN entfernen vorm anlegen {{ vlanid }}
    community.routeros.command:
      commands: /interface/bridge/vlan/remove [find vlan-ids={{ vlanid }}]

  - name: VLAN Add Bridge {{ vlanid }}
    community.routeros.command:
      commands:
        - "/interface/bridge/vlan/add vlan-id={{ vlanid }} bridge={{ bridgeid }} tagged={{ taggedinterface }} untagged={{ untaggedinterface }} comment={{commentvar}}"


...
